const names = [
    'Aaran',
    'Aaren',
    'Aarez',
    'Aarman',
    'Aaron',
    'Aaron-James',
    'Aarron',
    'Aaryan',
    'Aaryn',
    'Aayan',
    'Aazaan',
    'Abaan',
    'Abbas',
    'Abdallah',
    'Abdalroof',
    'Abdihakim',
    'Abdirahman',
    'Abdisalam',
    'Abdul',
    'Abdul-Aziz',
    'Abdulbasir',
    'Abdulkadir',
    'Abdulkarem',
    'Smith',
    'Jones',
    'Coollastname',
    'enter_name_here',
    'Ze',
    'Zechariah',
    'Zeek',
    'Zeeshan',
    'Zeid',
    'Zein',
    'Zen',
    'Zendel',
    'Zenith',
    'Zennon',
    'Zeph',
    'Zerah',
    'Zhen',
    'Zhi',
    'Zhong',
    'Zhuo',
    'Zi',
    'Zidane',
    'Zijie',
    'Zinedine',
    'Zion',
    'Zishan',
    'Ziya',
    'Ziyaan',
    'Zohaib',
    'Zohair',
    'Zoubaeir',
    'Zubair',
    'Zubayr',
    'Zuriel',
    'Xander',
    'Jared',
    'Courtney',
    'Gillian',
    'Clark',
    'Jared',
    'Grace',
    'Kelsey',
    'Tamar',
    'Alex',
    'Mark',
    'Tamar',
    'Farish',
    'Sarah',
    'Nathaniel',
    'Parker',
    'Ozzy Osbourne',
    'Bruce Dickinson',
    'James Hetfield',
    'Dave Mustaine',
    'Kirk Hammett',
    'Tony Iommi',
    'Ronnie James Dio',
    'Rob Halford',
    'Lemmy Kilmister',
    'Alice Cooper',
    'Blackie Lawless',
    'Tom Araya',
    'Kerry King',
    'Jeff Hanneman',
    'Dave Lombardo',
    'Joey Jordison',
    'Corey Taylor',
    'Randy Blythe',
    'Chuck Schuldiner',
    'Dimebag Darrell',
    'Vinnie Paul',
    'Phil Anselmo',
    'Zakk Wylde',
    'Eddie Van Halen',
    'David Lee Roth',
    'Sammy Hagar',
    'Steve Harris',
    'Adrian Smith',
    'Janick Gers',
    'Nicko McBrain',
    'Paul Di\'Anno',
    'Bruce Kulick',
    'Gene Simmons',
    'Paul Stanley',
    'Ace Frehley',
    'Peter Criss',
    'Tommy Lee',
    'Vince Neil',
    'Mick Mars',
    'Nikki Sixx',
    'James Kottak',
    'Rudolf Schenker',
    'Klaus Meine',
    'Michael Schenker',
    'Phil Campbell',
    'Mikkey Dee',
    'Joey Belladonna',
    'Scott Ian',
    'Frank Bello',
    'Charlie Benante',
    'John Bush',
    'Joey Vera',  
];


